import time
print("LET'S PLAY A GK GAME")
time.sleep(2)
print("Enter your answer as a ,b ,c or d")
time.sleep(3)
print("Question 1:\nWho is hosting G20 2023 Summit ?")
time.sleep(4)
print("a) Indonesia          b)India \nc)Japan               d)Korea ")
time.sleep(3)
str(input("Enter your answer: "))
time.sleep(1)
print("The correct answer is b")
time.sleep(3)
print("Question 2: \nWhat is the National tree of India ?")
time.sleep(4)
print("a) Banyan tree        b)Indian Laburnum\nc)Arjun Tree           d)Ashok Tree")
time.sleep(3)
str(input("Enter your answer: "))
time.sleep(1)
print("The correct answer is a")
time.sleep(4)
print("Question 3: \nWho was Latta Mangeshwar ji: ?")
time.sleep(3)
print("a)A Politician      b)A singer \nc)A sister       d)A social worker")
time.sleep(3)
str(input("Enter your answer: "))
time.sleep(1)
print("The correct answer is b")
time.sleep(3)
print("Question 4: \nWho is current the PM of India: ?")
time.sleep(3)
print("a)Narendra Modi ji       b)Sonia Gnadhi \nc)Draupati Murmu        d)Rahul Gandhi")
time.sleep(3)
str(input("Enter your answer: "))
time.sleep(1)
print("The correct answer is a")
time.sleep(3)
print("Question 5: \nWho is the current President of India: ?")
time.sleep(3)
print("a)Narendra Modi ji       b)Draupadi Murmu \nc)Dr. Jai Shankar        d)Rahul Gandhi")
time.sleep(3)
str(input("Enter your answer: "))
time.sleep(1)
print("The correct answer is b")
time.sleep(3)
print("GAME OVER!")
